Install the **Numpy** package

In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 217.9 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 217.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.0 kB 245.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 270.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB 1.9 MB/s eta 0:00:09
   ---------------------------------------- 0.1/15.5 MB 648.1 kB/s eta 0:00:24
   ---------------------------------------- 0.1/15.5 MB 901.1 kB/s eta 0:00:18
   ---------------------------------------- 0.2/15.5 MB 1.1 MB/s eta 0:00:14
    --------------------------------------- 0.2/15.5 MB 935.2 kB/s eta 0:00:17
    --------------------------------------- 0.2/15.5 MB 901.1 kB/s eta 0:0

Import the **Numpy** package

In [2]:
import numpy as np

Create 1D array

In [5]:
data_1d = np.array([1, 2, 3, 4, 5])

Create 2D array

In [6]:
data_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

Print the Array shape

In [8]:
print(data_1d.shape)
print(data_2d.shape)

(5,)
(2, 4)


Reshape the Array

In [10]:
reshaped_arr = data_2d.reshape(4, 2)
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Print the array dimension

In [11]:
print(data_2d.ndim)

2


Array Indexing and slicing

In [16]:
#Indexing
print(data_1d[0])
print(data_1d[3])
print(data_2d[1,2])
print(data_2d[0,3])

1
4
7
4


In [18]:
#Slicing
print(data_1d[:3])
print(data_2d[:, 1:])

[1 2 3]
[[2 3 4]
 [6 7 8]]


Array Operations

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 9])

In [23]:
p = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
q = np.array([[9, 5, 5, 7], [3, 4, 9, 6]])

Addition


In [25]:
add = a + b
print("Add: ", add)


addd = p + q
print("Addd:", addd)

Add:  [ 6  8 10 13]
Addd: [[10  7  8 11]
 [ 8 10 16 14]]


Multiplication

In [26]:
print("1D Multi: ", a*b)
print("2D Multi: ", p*q)

1D Multi:  [ 5 12 21 36]
2D Multi:  [[ 9 10 15 28]
 [15 24 63 48]]


Find the exponential value

In [28]:
exp_a = np.exp(a)
print("exp_a: ", exp_a)

exp_p = np.exp(p)
print("exp_p: ", exp_p)

exp_a:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
exp_p:  [[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]


Find the Log value

In [30]:
log_a = np.log(a)
print("log_a: ", log_a)

log_p = np.log(p)
print("log_p: ", log_p)

log_a:  [0.         0.69314718 1.09861229 1.38629436]
log_p:  [[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]]


Broadcasting

In [33]:
a = np.array([1, 2, 3])
b = 10
result = a + b
print(result)

[11 12 13]


Array Aggregation

In [36]:
data = np.array([[1, 2, 3], [4, 5, 6]])
print("Summation of the whole array: ", np.sum(data))
print("Column wise summation: ", np.sum(data, axis=0))
print("Row wise mean: ", np.mean(data, axis=1))

Summation of the whole array:  21
Column wise summation:  [5 7 9]
Row wise mean:  [2. 5.]
